// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTasksCreatedBetween = `-- name: CountTasksCreatedBetween :one
SELECT COUNT(*)::bigint AS total
FROM tasks
WHERE user_id = $1
  AND created_at >= $2
  AND created_at < $3
  AND deleted_at IS NULL
`

type CountTasksCreatedBetweenParams struct {
	UserID      pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	CreatedAt_2 pgtype.Timestamptz
}

func (q *Queries) CountTasksCreatedBetween(ctx context.Context, arg CountTasksCreatedBetweenParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTasksCreatedBetween, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countUserHabits = `-- name: CountUserHabits :one
SELECT COUNT(*)::bigint AS total
FROM habits
WHERE user_id = $1
`

func (q *Queries) CountUserHabits(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserHabits, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}
