// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calendar_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertCalendarEvent = `-- name: InsertCalendarEvent :exec
INSERT INTO calendar_events (id, user_id, title, starts_at, ends_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertCalendarEventParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Title     string
	StartsAt  pgtype.Timestamptz
	EndsAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertCalendarEvent(ctx context.Context, arg InsertCalendarEventParams) error {
	_, err := q.db.Exec(ctx, insertCalendarEvent,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.StartsAt,
		arg.EndsAt,
		arg.CreatedAt,
	)
	return err
}

const listCalendarEventsBetween = `-- name: ListCalendarEventsBetween :many
SELECT id, user_id, title, starts_at, ends_at, created_at
FROM calendar_events
WHERE user_id = $1 AND starts_at >= $2 AND starts_at < $3
ORDER BY starts_at ASC
`

type ListCalendarEventsBetweenParams struct {
	UserID     pgtype.UUID
	StartsAt   pgtype.Timestamptz
	StartsAt_2 pgtype.Timestamptz
}

func (q *Queries) ListCalendarEventsBetween(ctx context.Context, arg ListCalendarEventsBetweenParams) ([]CalendarEvent, error) {
	rows, err := q.db.Query(ctx, listCalendarEventsBetween, arg.UserID, arg.StartsAt, arg.StartsAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarEvent{}
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
