// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: career_skills.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSkillByUser = `-- name: DeleteSkillByUser :one
DELETE FROM career_skills
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, level, created_at, updated_at
`

type DeleteSkillByUserParams struct {
	SkillID pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) DeleteSkillByUser(ctx context.Context, arg DeleteSkillByUserParams) (CareerSkill, error) {
	row := q.db.QueryRow(ctx, deleteSkillByUser, arg.SkillID, arg.UserID)
	var i CareerSkill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Level,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSkill = `-- name: InsertSkill :exec
INSERT INTO career_skills (id, user_id, name, level, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertSkillParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	Level     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) InsertSkill(ctx context.Context, arg InsertSkillParams) error {
	_, err := q.db.Exec(ctx, insertSkill,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Level,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listRecentSkillsByUser = `-- name: ListRecentSkillsByUser :many
SELECT id, user_id, name, level, created_at, updated_at
FROM career_skills
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListRecentSkillsByUserParams struct {
	UserID pgtype.UUID
	Limit  int32
}

func (q *Queries) ListRecentSkillsByUser(ctx context.Context, arg ListRecentSkillsByUserParams) ([]CareerSkill, error) {
	rows, err := q.db.Query(ctx, listRecentSkillsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CareerSkill{}
	for rows.Next() {
		var i CareerSkill
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Level,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSkillsByUser = `-- name: SearchSkillsByUser :many
SELECT id, user_id, name, level, created_at, updated_at
FROM career_skills
WHERE user_id = $1
  AND (
    name ILIKE '%' || $2 || '%'
    OR level ILIKE '%' || $2 || '%'
  )
ORDER BY created_at DESC
LIMIT $3
`

type SearchSkillsByUserParams struct {
	UserID      pgtype.UUID
	Query       pgtype.Text
	ResultLimit int32
}

func (q *Queries) SearchSkillsByUser(ctx context.Context, arg SearchSkillsByUserParams) ([]CareerSkill, error) {
	rows, err := q.db.Query(ctx, searchSkillsByUser, arg.UserID, arg.Query, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CareerSkill{}
	for rows.Next() {
		var i CareerSkill
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Level,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
