// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: career_contacts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteContactByUser = `-- name: DeleteContactByUser :one
DELETE FROM career_contacts
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, company, role, notes, created_at, updated_at
`

type DeleteContactByUserParams struct {
	ContactID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) DeleteContactByUser(ctx context.Context, arg DeleteContactByUserParams) (CareerContact, error) {
	row := q.db.QueryRow(ctx, deleteContactByUser, arg.ContactID, arg.UserID)
	var i CareerContact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Company,
		&i.Role,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertContact = `-- name: InsertContact :exec
INSERT INTO career_contacts (id, user_id, name, company, role, notes, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertContactParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	Company   string
	Role      string
	Notes     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) InsertContact(ctx context.Context, arg InsertContactParams) error {
	_, err := q.db.Exec(ctx, insertContact,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Company,
		arg.Role,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listRecentContactsByUser = `-- name: ListRecentContactsByUser :many
SELECT id, user_id, name, company, role, notes, created_at, updated_at
FROM career_contacts
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListRecentContactsByUserParams struct {
	UserID pgtype.UUID
	Limit  int32
}

func (q *Queries) ListRecentContactsByUser(ctx context.Context, arg ListRecentContactsByUserParams) ([]CareerContact, error) {
	rows, err := q.db.Query(ctx, listRecentContactsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CareerContact{}
	for rows.Next() {
		var i CareerContact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Company,
			&i.Role,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchContactsByUser = `-- name: SearchContactsByUser :many
SELECT id, user_id, name, company, role, notes, created_at, updated_at
FROM career_contacts
WHERE user_id = $1
  AND (
    name ILIKE '%' || $2 || '%'
    OR company ILIKE '%' || $2 || '%'
    OR role ILIKE '%' || $2 || '%'
  )
ORDER BY created_at DESC
LIMIT $3
`

type SearchContactsByUserParams struct {
	UserID      pgtype.UUID
	Query       pgtype.Text
	ResultLimit int32
}

func (q *Queries) SearchContactsByUser(ctx context.Context, arg SearchContactsByUserParams) ([]CareerContact, error) {
	rows, err := q.db.Query(ctx, searchContactsByUser, arg.UserID, arg.Query, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CareerContact{}
	for rows.Next() {
		var i CareerContact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Company,
			&i.Role,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
