// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: day_availability.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDayAvailability = `-- name: GetDayAvailability :one
SELECT id, user_id, day, available_until, note, created_at
FROM day_availability
WHERE user_id = $1 AND day = $2
`

type GetDayAvailabilityParams struct {
	UserID pgtype.UUID
	Day    pgtype.Date
}

func (q *Queries) GetDayAvailability(ctx context.Context, arg GetDayAvailabilityParams) (DayAvailability, error) {
	row := q.db.QueryRow(ctx, getDayAvailability, arg.UserID, arg.Day)
	var i DayAvailability
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Day,
		&i.AvailableUntil,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const upsertDayAvailability = `-- name: UpsertDayAvailability :one
INSERT INTO day_availability (id, user_id, day, available_until, note, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, day) DO UPDATE
SET available_until = EXCLUDED.available_until,
    note = EXCLUDED.note
RETURNING id, user_id, day, available_until, note, created_at
`

type UpsertDayAvailabilityParams struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	Day            pgtype.Date
	AvailableUntil pgtype.Time
	Note           pgtype.Text
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) UpsertDayAvailability(ctx context.Context, arg UpsertDayAvailabilityParams) (DayAvailability, error) {
	row := q.db.QueryRow(ctx, upsertDayAvailability,
		arg.ID,
		arg.UserID,
		arg.Day,
		arg.AvailableUntil,
		arg.Note,
		arg.CreatedAt,
	)
	var i DayAvailability
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Day,
		&i.AvailableUntil,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}
