// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: debts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findOpenDebtByCreditor = `-- name: FindOpenDebtByCreditor :one
SELECT id, user_id, creditor, amount_cents, paid_cents, due_date, status, created_at
FROM debts
WHERE user_id = $1 AND status = 'open' AND creditor ILIKE '%' || $2 || '%'
ORDER BY
    CASE WHEN lower(creditor) = lower($2) THEN 0 ELSE 1 END,
    created_at ASC
LIMIT 1
`

type FindOpenDebtByCreditorParams struct {
	UserID  pgtype.UUID
	Column2 pgtype.Text
}

func (q *Queries) FindOpenDebtByCreditor(ctx context.Context, arg FindOpenDebtByCreditorParams) (Debt, error) {
	row := q.db.QueryRow(ctx, findOpenDebtByCreditor, arg.UserID, arg.Column2)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Creditor,
		&i.AmountCents,
		&i.PaidCents,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getDebtByID = `-- name: GetDebtByID :one
SELECT id, user_id, creditor, amount_cents, paid_cents, due_date, status, created_at
FROM debts
WHERE id = $1 AND user_id = $2
`

type GetDebtByIDParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetDebtByID(ctx context.Context, arg GetDebtByIDParams) (Debt, error) {
	row := q.db.QueryRow(ctx, getDebtByID, arg.ID, arg.UserID)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Creditor,
		&i.AmountCents,
		&i.PaidCents,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertDebt = `-- name: InsertDebt :exec
INSERT INTO debts (id, user_id, creditor, amount_cents, paid_cents, due_date, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertDebtParams struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Creditor    string
	AmountCents int64
	PaidCents   int64
	DueDate     pgtype.Date
	Status      string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertDebt(ctx context.Context, arg InsertDebtParams) error {
	_, err := q.db.Exec(ctx, insertDebt,
		arg.ID,
		arg.UserID,
		arg.Creditor,
		arg.AmountCents,
		arg.PaidCents,
		arg.DueDate,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const listOpenDebts = `-- name: ListOpenDebts :many
SELECT id, user_id, creditor, amount_cents, paid_cents, due_date, status, created_at
FROM debts
WHERE user_id = $1 AND status = 'open'
LIMIT 1
`

func (q *Queries) ListOpenDebts(ctx context.Context, userID pgtype.UUID) ([]Debt, error) {
	rows, err := q.db.Query(ctx, listOpenDebts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Debt{}
	for rows.Next() {
		var i Debt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Creditor,
			&i.AmountCents,
			&i.PaidCents,
			&i.DueDate,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDebt = `-- name: UpdateDebt :exec
UPDATE debts
SET paid_cents = $3, status = $4
WHERE id = $1 AND user_id = $2
`

type UpdateDebtParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	PaidCents int64
	Status    string
}

func (q *Queries) UpdateDebt(ctx context.Context, arg UpdateDebtParams) error {
	_, err := q.db.Exec(ctx, updateDebt,
		arg.ID,
		arg.UserID,
		arg.PaidCents,
		arg.Status,
	)
	return err
}
