// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertDomainEvent = `-- name: InsertDomainEvent :exec
INSERT INTO domain_events (
    id, user_id, aggregate_type, aggregate_id, event_type, payload, source, occurred_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type InsertDomainEventParams struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	AggregateType string
	AggregateID   pgtype.UUID
	EventType     string
	Payload       []byte
	Source        string
	OccurredAt    pgtype.Timestamptz
}

func (q *Queries) InsertDomainEvent(ctx context.Context, arg InsertDomainEventParams) error {
	_, err := q.db.Exec(ctx, insertDomainEvent,
		arg.ID,
		arg.UserID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.Source,
		arg.OccurredAt,
	)
	return err
}
