// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finance_transactions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertFinanceTransaction = `-- name: InsertFinanceTransaction :exec
INSERT INTO finance_transactions (
    id, user_id, category_id, kind, amount_cents, currency, description, occurred_at, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertFinanceTransactionParams struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	CategoryID  pgtype.UUID
	Kind        string
	AmountCents int64
	Currency    string
	Description pgtype.Text
	OccurredAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertFinanceTransaction(ctx context.Context, arg InsertFinanceTransactionParams) error {
	_, err := q.db.Exec(ctx, insertFinanceTransaction,
		arg.ID,
		arg.UserID,
		arg.CategoryID,
		arg.Kind,
		arg.AmountCents,
		arg.Currency,
		arg.Description,
		arg.OccurredAt,
		arg.CreatedAt,
	)
	return err
}

const sumExpenseBetween = `-- name: SumExpenseBetween :one
SELECT COALESCE(SUM(amount_cents), 0)::bigint AS total
FROM finance_transactions
WHERE user_id = $1
  AND kind = 'expense'
  AND occurred_at >= $2
  AND occurred_at < $3
`

type SumExpenseBetweenParams struct {
	UserID       pgtype.UUID
	OccurredAt   pgtype.Timestamptz
	OccurredAt_2 pgtype.Timestamptz
}

func (q *Queries) SumExpenseBetween(ctx context.Context, arg SumExpenseBetweenParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumExpenseBetween, arg.UserID, arg.OccurredAt, arg.OccurredAt_2)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const sumExpensesByCategoryBetween = `-- name: SumExpensesByCategoryBetween :many
SELECT c.name AS name, COALESCE(SUM(t.amount_cents), 0)::bigint AS amount_cents
FROM finance_transactions t
JOIN finance_categories c ON c.id = t.category_id
WHERE t.user_id = $1
  AND t.kind = 'expense'
  AND t.occurred_at >= $2
  AND t.occurred_at < $3
GROUP BY c.name
ORDER BY amount_cents DESC, c.name ASC
`

type SumExpensesByCategoryBetweenParams struct {
	UserID       pgtype.UUID
	OccurredAt   pgtype.Timestamptz
	OccurredAt_2 pgtype.Timestamptz
}

type SumExpensesByCategoryBetweenRow struct {
	Name        string
	AmountCents int64
}

func (q *Queries) SumExpensesByCategoryBetween(ctx context.Context, arg SumExpensesByCategoryBetweenParams) ([]SumExpensesByCategoryBetweenRow, error) {
	rows, err := q.db.Query(ctx, sumExpensesByCategoryBetween, arg.UserID, arg.OccurredAt, arg.OccurredAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumExpensesByCategoryBetweenRow{}
	for rows.Next() {
		var i SumExpensesByCategoryBetweenRow
		if err := rows.Scan(&i.Name, &i.AmountCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumIncomeBetween = `-- name: SumIncomeBetween :one
SELECT COALESCE(SUM(amount_cents), 0)::bigint AS total
FROM finance_transactions
WHERE user_id = $1
  AND kind = 'income'
  AND occurred_at >= $2
  AND occurred_at < $3
`

type SumIncomeBetweenParams struct {
	UserID       pgtype.UUID
	OccurredAt   pgtype.Timestamptz
	OccurredAt_2 pgtype.Timestamptz
}

func (q *Queries) SumIncomeBetween(ctx context.Context, arg SumIncomeBetweenParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumIncomeBetween, arg.UserID, arg.OccurredAt, arg.OccurredAt_2)
	var total int64
	err := row.Scan(&total)
	return total, err
}
