// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finance_categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFinanceCategoryByName = `-- name: GetFinanceCategoryByName :one
SELECT id, user_id, name, kind, created_at
FROM finance_categories
WHERE user_id = $1 AND name = $2 AND kind = $3
`

type GetFinanceCategoryByNameParams struct {
	UserID pgtype.UUID
	Name   string
	Kind   string
}

func (q *Queries) GetFinanceCategoryByName(ctx context.Context, arg GetFinanceCategoryByNameParams) (FinanceCategory, error) {
	row := q.db.QueryRow(ctx, getFinanceCategoryByName, arg.UserID, arg.Name, arg.Kind)
	var i FinanceCategory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const insertFinanceCategory = `-- name: InsertFinanceCategory :exec
INSERT INTO finance_categories (id, user_id, name, kind, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertFinanceCategoryParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	Kind      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertFinanceCategory(ctx context.Context, arg InsertFinanceCategoryParams) error {
	_, err := q.db.Exec(ctx, insertFinanceCategory,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Kind,
		arg.CreatedAt,
	)
	return err
}
