// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: habit_logs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listHabitLogsSince = `-- name: ListHabitLogsSince :many
SELECT id, habit_id, log_date, completed, created_at
FROM habit_logs
WHERE habit_id = $1 AND log_date >= $2
ORDER BY log_date DESC
`

type ListHabitLogsSinceParams struct {
	HabitID pgtype.UUID
	LogDate pgtype.Date
}

func (q *Queries) ListHabitLogsSince(ctx context.Context, arg ListHabitLogsSinceParams) ([]HabitLog, error) {
	rows, err := q.db.Query(ctx, listHabitLogsSince, arg.HabitID, arg.LogDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HabitLog{}
	for rows.Next() {
		var i HabitLog
		if err := rows.Scan(
			&i.ID,
			&i.HabitID,
			&i.LogDate,
			&i.Completed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHabitsWithTodayLog = `-- name: ListHabitsWithTodayLog :many
SELECT
    h.id,
    h.user_id,
    h.name,
    h.frequency,
    h.created_at,
    hl.completed AS today_completed
FROM habits h
LEFT JOIN habit_logs hl ON hl.habit_id = h.id AND hl.log_date = $2
WHERE h.user_id = $1
ORDER BY h.created_at ASC
`

type ListHabitsWithTodayLogParams struct {
	UserID  pgtype.UUID
	LogDate pgtype.Date
}

type ListHabitsWithTodayLogRow struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	Name           string
	Frequency      string
	CreatedAt      pgtype.Timestamptz
	TodayCompleted pgtype.Bool
}

func (q *Queries) ListHabitsWithTodayLog(ctx context.Context, arg ListHabitsWithTodayLogParams) ([]ListHabitsWithTodayLogRow, error) {
	rows, err := q.db.Query(ctx, listHabitsWithTodayLog, arg.UserID, arg.LogDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHabitsWithTodayLogRow{}
	for rows.Next() {
		var i ListHabitsWithTodayLogRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Frequency,
			&i.CreatedAt,
			&i.TodayCompleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHabitLog = `-- name: UpsertHabitLog :exec
INSERT INTO habit_logs (id, habit_id, log_date, completed, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (habit_id, log_date) DO UPDATE
SET completed = EXCLUDED.completed
`

type UpsertHabitLogParams struct {
	ID        pgtype.UUID
	HabitID   pgtype.UUID
	LogDate   pgtype.Date
	Completed bool
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) UpsertHabitLog(ctx context.Context, arg UpsertHabitLogParams) error {
	_, err := q.db.Exec(ctx, upsertHabitLog,
		arg.ID,
		arg.HabitID,
		arg.LogDate,
		arg.Completed,
		arg.CreatedAt,
	)
	return err
}
