// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: habits.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findHabitByName = `-- name: FindHabitByName :one
SELECT id, user_id, name, frequency, start_date, end_date, created_at
FROM habits
WHERE user_id = $1 AND lower(name) = lower($2)
`

type FindHabitByNameParams struct {
	UserID pgtype.UUID
	Lower  string
}

func (q *Queries) FindHabitByName(ctx context.Context, arg FindHabitByNameParams) (Habit, error) {
	row := q.db.QueryRow(ctx, findHabitByName, arg.UserID, arg.Lower)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Frequency,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

const getHabitByID = `-- name: GetHabitByID :one
SELECT id, user_id, name, frequency, start_date, end_date, created_at
FROM habits
WHERE id = $1 AND user_id = $2
`

type GetHabitByIDParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetHabitByID(ctx context.Context, arg GetHabitByIDParams) (Habit, error) {
	row := q.db.QueryRow(ctx, getHabitByID, arg.ID, arg.UserID)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Frequency,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

const insertHabit = `-- name: InsertHabit :exec
INSERT INTO habits (id, user_id, name, frequency, start_date, end_date, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertHabitParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	Frequency string
	StartDate pgtype.Date
	EndDate   pgtype.Date
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertHabit(ctx context.Context, arg InsertHabitParams) error {
	_, err := q.db.Exec(ctx, insertHabit,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Frequency,
		arg.StartDate,
		arg.EndDate,
		arg.CreatedAt,
	)
	return err
}

const listHabits = `-- name: ListHabits :many
SELECT id, user_id, name, frequency, start_date, end_date, created_at
FROM habits
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListHabits(ctx context.Context, userID pgtype.UUID) ([]Habit, error) {
	rows, err := q.db.Query(ctx, listHabits, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Habit{}
	for rows.Next() {
		var i Habit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Frequency,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHabit = `-- name: UpdateHabit :execrows
UPDATE habits
SET name = $3,
    frequency = $4,
    start_date = $5,
    end_date = $6
WHERE id = $1 AND user_id = $2
`

type UpdateHabitParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	Frequency string
	StartDate pgtype.Date
	EndDate   pgtype.Date
}

func (q *Queries) UpdateHabit(ctx context.Context, arg UpdateHabitParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateHabit,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Frequency,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteHabit = `-- name: DeleteHabit :execrows
DELETE FROM habits
WHERE id = $1 AND user_id = $2
`

type DeleteHabitParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteHabit(ctx context.Context, arg DeleteHabitParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHabit, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
