// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health_sleep.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestSleepByUser = `-- name: GetLatestSleepByUser :one
SELECT id, user_id, duration_minutes, logged_at, created_at
FROM health_sleep_logs
WHERE user_id = $1
ORDER BY logged_at DESC
LIMIT 1
`

func (q *Queries) GetLatestSleepByUser(ctx context.Context, userID pgtype.UUID) (HealthSleepLog, error) {
	row := q.db.QueryRow(ctx, getLatestSleepByUser, userID)
	var i HealthSleepLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DurationMinutes,
		&i.LoggedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertSleepLog = `-- name: InsertSleepLog :exec
INSERT INTO health_sleep_logs (id, user_id, duration_minutes, logged_at, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertSleepLogParams struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	DurationMinutes int32
	LoggedAt        pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) InsertSleepLog(ctx context.Context, arg InsertSleepLogParams) error {
	_, err := q.db.Exec(ctx, insertSleepLog,
		arg.ID,
		arg.UserID,
		arg.DurationMinutes,
		arg.LoggedAt,
		arg.CreatedAt,
	)
	return err
}

const listRecentSleepByUser = `-- name: ListRecentSleepByUser :many
SELECT id, user_id, duration_minutes, logged_at, created_at
FROM health_sleep_logs
WHERE user_id = $1
ORDER BY logged_at DESC
LIMIT $2
`

type ListRecentSleepByUserParams struct {
	UserID pgtype.UUID
	Limit  int32
}

func (q *Queries) ListRecentSleepByUser(ctx context.Context, arg ListRecentSleepByUserParams) ([]HealthSleepLog, error) {
	rows, err := q.db.Query(ctx, listRecentSleepByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HealthSleepLog{}
	for rows.Next() {
		var i HealthSleepLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DurationMinutes,
			&i.LoggedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
