// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health_weight.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestWeightByUser = `-- name: GetLatestWeightByUser :one
SELECT id, user_id, weight_kg, logged_at, created_at
FROM health_weight_logs
WHERE user_id = $1
ORDER BY logged_at DESC
LIMIT 1
`

func (q *Queries) GetLatestWeightByUser(ctx context.Context, userID pgtype.UUID) (HealthWeightLog, error) {
	row := q.db.QueryRow(ctx, getLatestWeightByUser, userID)
	var i HealthWeightLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeightKg,
		&i.LoggedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertWeightLog = `-- name: InsertWeightLog :exec
INSERT INTO health_weight_logs (id, user_id, weight_kg, logged_at, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertWeightLogParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	WeightKg  float64
	LoggedAt  pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertWeightLog(ctx context.Context, arg InsertWeightLogParams) error {
	_, err := q.db.Exec(ctx, insertWeightLog,
		arg.ID,
		arg.UserID,
		arg.WeightKg,
		arg.LoggedAt,
		arg.CreatedAt,
	)
	return err
}

const listRecentWeightsByUser = `-- name: ListRecentWeightsByUser :many
SELECT id, user_id, weight_kg, logged_at, created_at
FROM health_weight_logs
WHERE user_id = $1
ORDER BY logged_at DESC
LIMIT $2
`

type ListRecentWeightsByUserParams struct {
	UserID pgtype.UUID
	Limit  int32
}

func (q *Queries) ListRecentWeightsByUser(ctx context.Context, arg ListRecentWeightsByUserParams) ([]HealthWeightLog, error) {
	rows, err := q.db.Query(ctx, listRecentWeightsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HealthWeightLog{}
	for rows.Next() {
		var i HealthWeightLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WeightKg,
			&i.LoggedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
