// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health_steps.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestStepsByUser = `-- name: GetLatestStepsByUser :one
SELECT id, user_id, steps, logged_at, created_at
FROM health_step_logs
WHERE user_id = $1
ORDER BY logged_at DESC
LIMIT 1
`

func (q *Queries) GetLatestStepsByUser(ctx context.Context, userID pgtype.UUID) (HealthStepLog, error) {
	row := q.db.QueryRow(ctx, getLatestStepsByUser, userID)
	var i HealthStepLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Steps,
		&i.LoggedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertStepLog = `-- name: InsertStepLog :exec
INSERT INTO health_step_logs (id, user_id, steps, logged_at, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertStepLogParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Steps     int32
	LoggedAt  pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertStepLog(ctx context.Context, arg InsertStepLogParams) error {
	_, err := q.db.Exec(ctx, insertStepLog,
		arg.ID,
		arg.UserID,
		arg.Steps,
		arg.LoggedAt,
		arg.CreatedAt,
	)
	return err
}

const listRecentStepsByUser = `-- name: ListRecentStepsByUser :many
SELECT id, user_id, steps, logged_at, created_at
FROM health_step_logs
WHERE user_id = $1
ORDER BY logged_at DESC
LIMIT $2
`

type ListRecentStepsByUserParams struct {
	UserID pgtype.UUID
	Limit  int32
}

func (q *Queries) ListRecentStepsByUser(ctx context.Context, arg ListRecentStepsByUserParams) ([]HealthStepLog, error) {
	rows, err := q.db.Query(ctx, listRecentStepsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HealthStepLog{}
	for rows.Next() {
		var i HealthStepLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Steps,
			&i.LoggedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
