// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CalendarEvent struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Title     string
	StartsAt  pgtype.Timestamptz
	EndsAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type CareerContact struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	Company   string
	Role      string
	Notes     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type CareerSkill struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	Level     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type DayAvailability struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	Day            pgtype.Date
	AvailableUntil pgtype.Time
	Note           pgtype.Text
	CreatedAt      pgtype.Timestamptz
}

type Debt struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Creditor    string
	AmountCents int64
	PaidCents   int64
	DueDate     pgtype.Date
	Status      string
	CreatedAt   pgtype.Timestamptz
}

type DomainEvent struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	AggregateType string
	AggregateID   pgtype.UUID
	EventType     string
	Payload       []byte
	Source        string
	OccurredAt    pgtype.Timestamptz
}

type FinanceCategory struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	Kind      string
	CreatedAt pgtype.Timestamptz
}

type FinanceTransaction struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	CategoryID  pgtype.UUID
	Kind        string
	AmountCents int64
	Currency    string
	Description pgtype.Text
	OccurredAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type Habit struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	Frequency string
	CreatedAt pgtype.Timestamptz
}

type HabitLog struct {
	ID        pgtype.UUID
	HabitID   pgtype.UUID
	LogDate   pgtype.Date
	Completed bool
	CreatedAt pgtype.Timestamptz
}

type HealthSleepLog struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	DurationMinutes int32
	LoggedAt        pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

type HealthStepLog struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Steps     int32
	LoggedAt  pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type HealthWeightLog struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	WeightKg  float64
	LoggedAt  pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type LifeSphere struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	SortOrder int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Note struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Body      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Tags      []string
}

type ProcessedUpdate struct {
	UpdateID    int64
	ProcessedAt pgtype.Timestamptz
}

type Project struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Name         string
	Description  pgtype.Text
	Status       string
	CreatedAt    pgtype.Timestamptz
	Outcome      pgtype.Text
	TargetValue  pgtype.Numeric
	CurrentValue pgtype.Numeric
	Unit         pgtype.Text
	TargetDate   pgtype.Date
	UpdatedAt    pgtype.Timestamptz
}

type ProjectSphere struct {
	ProjectID pgtype.UUID
	SphereID  pgtype.UUID
}

type ScheduledJob struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	JobType    string
	Payload    []byte
	RunAt      pgtype.Timestamptz
	Status     string
	RetryCount int32
	Channel    string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Task struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	Title           string
	Description     pgtype.Text
	Status          string
	Priority        string
	DueDate         pgtype.Date
	CompletedAt     pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DurationMinutes pgtype.Int4
	Tags            []string
}

type TaskProject struct {
	TaskID    pgtype.UUID
	ProjectID pgtype.UUID
}

type TelegramSession struct {
	UserID             pgtype.UUID
	ChatID             int64
	DashboardMessageID pgtype.Int8
	State              string
	StatePayload       []byte
	UpdatedAt          pgtype.Timestamptz
}

type User struct {
	ID          pgtype.UUID
	TelegramID  int64
	DisplayName string
	Timezone    string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type UserSetting struct {
	UserID          pgtype.UUID
	MorningReviewAt pgtype.Time
	EveningReviewAt pgtype.Time
	QuietHoursStart pgtype.Time
	QuietHoursEnd   pgtype.Time
	Language        string
	UpdatedAt       pgtype.Timestamptz
	WeeklyReviewAt  pgtype.Time
	MonthlyReviewAt pgtype.Time
}
