// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteNoteByUser = `-- name: DeleteNoteByUser :one
DELETE FROM notes
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, body, tags, created_at, updated_at
`

type DeleteNoteByUserParams struct {
	NoteID pgtype.UUID
	UserID pgtype.UUID
}

type DeleteNoteByUserRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Body      string
	Tags      []string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) DeleteNoteByUser(ctx context.Context, arg DeleteNoteByUserParams) (DeleteNoteByUserRow, error) {
	row := q.db.QueryRow(ctx, deleteNoteByUser, arg.NoteID, arg.UserID)
	var i DeleteNoteByUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Body,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertNote = `-- name: InsertNote :exec
INSERT INTO notes (id, user_id, body, tags, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertNoteParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Body      string
	Tags      []string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) InsertNote(ctx context.Context, arg InsertNoteParams) error {
	_, err := q.db.Exec(ctx, insertNote,
		arg.ID,
		arg.UserID,
		arg.Body,
		arg.Tags,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listNotesByTag = `-- name: ListNotesByTag :many
SELECT id, user_id, body, tags, created_at, updated_at
FROM notes
WHERE user_id = $1 AND $2::text = ANY(tags)
ORDER BY created_at DESC
LIMIT $3
`

type ListNotesByTagParams struct {
	UserID      pgtype.UUID
	Tag         string
	ResultLimit int32
}

type ListNotesByTagRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Body      string
	Tags      []string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListNotesByTag(ctx context.Context, arg ListNotesByTagParams) ([]ListNotesByTagRow, error) {
	rows, err := q.db.Query(ctx, listNotesByTag, arg.UserID, arg.Tag, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotesByTagRow{}
	for rows.Next() {
		var i ListNotesByTagRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Body,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentNotesByUser = `-- name: ListRecentNotesByUser :many
SELECT id, user_id, body, tags, created_at, updated_at
FROM notes
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListRecentNotesByUserParams struct {
	UserID pgtype.UUID
	Limit  int32
}

type ListRecentNotesByUserRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Body      string
	Tags      []string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListRecentNotesByUser(ctx context.Context, arg ListRecentNotesByUserParams) ([]ListRecentNotesByUserRow, error) {
	rows, err := q.db.Query(ctx, listRecentNotesByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentNotesByUserRow{}
	for rows.Next() {
		var i ListRecentNotesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Body,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchNotesByUser = `-- name: SearchNotesByUser :many
SELECT id, user_id, body, tags, created_at, updated_at
FROM notes
WHERE user_id = $1 AND body ILIKE '%' || $2 || '%'
ORDER BY created_at DESC
LIMIT $3
`

type SearchNotesByUserParams struct {
	UserID      pgtype.UUID
	Query       pgtype.Text
	ResultLimit int32
}

type SearchNotesByUserRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Body      string
	Tags      []string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) SearchNotesByUser(ctx context.Context, arg SearchNotesByUserParams) ([]SearchNotesByUserRow, error) {
	rows, err := q.db.Query(ctx, searchNotesByUser, arg.UserID, arg.Query, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchNotesByUserRow{}
	for rows.Next() {
		var i SearchNotesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Body,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
