// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: planned_cashflows.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePlannedCashflowByUser = `-- name: DeletePlannedCashflowByUser :one
DELETE FROM planned_cashflows
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, kind, title, amount_cents, interval, next_date, debt_id, created_at, updated_at
`

type DeletePlannedCashflowByUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeletePlannedCashflowByUser(ctx context.Context, arg DeletePlannedCashflowByUserParams) (PlannedCashflow, error) {
	row := q.db.QueryRow(ctx, deletePlannedCashflowByUser, arg.ID, arg.UserID)
	var i PlannedCashflow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Title,
		&i.AmountCents,
		&i.Interval,
		&i.NextDate,
		&i.DebtID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPlannedCashflow = `-- name: InsertPlannedCashflow :exec
INSERT INTO planned_cashflows (
    id, user_id, kind, title, amount_cents, interval, next_date, debt_id, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $9
)
`

type InsertPlannedCashflowParams struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Kind        string
	Title       string
	AmountCents int64
	Interval    string
	NextDate    pgtype.Date
	DebtID      pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertPlannedCashflow(ctx context.Context, arg InsertPlannedCashflowParams) error {
	_, err := q.db.Exec(ctx, insertPlannedCashflow,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.Title,
		arg.AmountCents,
		arg.Interval,
		arg.NextDate,
		arg.DebtID,
		arg.CreatedAt,
	)
	return err
}

const listPlannedCashflowsByUser = `-- name: ListPlannedCashflowsByUser :many
SELECT id, user_id, kind, title, amount_cents, interval, next_date, debt_id, created_at, updated_at
FROM planned_cashflows
WHERE user_id = $1
ORDER BY next_date ASC, created_at ASC
`

func (q *Queries) ListPlannedCashflowsByUser(ctx context.Context, userID pgtype.UUID) ([]PlannedCashflow, error) {
	rows, err := q.db.Query(ctx, listPlannedCashflowsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlannedCashflow{}
	for rows.Next() {
		var i PlannedCashflow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Title,
			&i.AmountCents,
			&i.Interval,
			&i.NextDate,
			&i.DebtID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
