// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: priorities.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listOverdueAndTodayTasks = `-- name: ListOverdueAndTodayTasks :many
SELECT id, user_id, title, description, status, priority, due_date,
       completed_at, deleted_at, created_at, updated_at, duration_minutes, tags, kind, address, note_id
FROM tasks
WHERE user_id = $1
  AND deleted_at IS NULL
  AND status IN ('todo', 'in_progress')
  AND (due_date <= $2 OR priority IN ('urgent', 'high'))
ORDER BY
    CASE priority WHEN 'urgent' THEN 4 WHEN 'high' THEN 3 WHEN 'medium' THEN 2 ELSE 1 END DESC,
    due_date ASC NULLS LAST,
    created_at ASC
`

type ListOverdueAndTodayTasksParams struct {
	UserID  pgtype.UUID
	DueDate pgtype.Date
}

func (q *Queries) ListOverdueAndTodayTasks(ctx context.Context, arg ListOverdueAndTodayTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listOverdueAndTodayTasks, arg.UserID, arg.DueDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.CompletedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DurationMinutes,
			&i.Tags,
			&i.Kind,
			&i.Address,
			&i.NoteID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksForDay = `-- name: ListTasksForDay :many
SELECT id, user_id, title, description, status, priority, due_date,
       completed_at, deleted_at, created_at, updated_at, duration_minutes, tags, kind, address, note_id
FROM tasks
WHERE user_id = $1
  AND deleted_at IS NULL
  AND due_date = $2
  AND status IN ('todo', 'in_progress')
ORDER BY
    CASE priority WHEN 'urgent' THEN 4 WHEN 'high' THEN 3 WHEN 'medium' THEN 2 ELSE 1 END DESC,
    created_at ASC
`

type ListTasksForDayParams struct {
	UserID  pgtype.UUID
	DueDate pgtype.Date
}

func (q *Queries) ListTasksForDay(ctx context.Context, arg ListTasksForDayParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksForDay, arg.UserID, arg.DueDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.CompletedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DurationMinutes,
			&i.Tags,
			&i.Kind,
			&i.Address,
			&i.NoteID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
