// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: processed_updates.sql

package db

import (
	"context"
)

const insertProcessedUpdate = `-- name: InsertProcessedUpdate :exec
INSERT INTO processed_updates (update_id) VALUES ($1)
`

func (q *Queries) InsertProcessedUpdate(ctx context.Context, updateID int64) error {
	_, err := q.db.Exec(ctx, insertProcessedUpdate, updateID)
	return err
}

const processedUpdateExists = `-- name: ProcessedUpdateExists :one
SELECT EXISTS (
    SELECT 1 FROM processed_updates WHERE update_id = $1
) AS exists
`

func (q *Queries) ProcessedUpdateExists(ctx context.Context, updateID int64) (bool, error) {
	row := q.db.QueryRow(ctx, processedUpdateExists, updateID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
