// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_spheres.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProjectsBySphere = `-- name: CountProjectsBySphere :one
SELECT count(*)::int
FROM project_spheres ps
JOIN projects p ON p.id = ps.project_id
WHERE ps.sphere_id = $1 AND p.status = 'active'
`

func (q *Queries) CountProjectsBySphere(ctx context.Context, sphereID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countProjectsBySphere, sphereID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteProjectSpheres = `-- name: DeleteProjectSpheres :exec
DELETE FROM project_spheres WHERE project_id = $1
`

func (q *Queries) DeleteProjectSpheres(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectSpheres, projectID)
	return err
}

const insertProjectSphere = `-- name: InsertProjectSphere :exec
INSERT INTO project_spheres (project_id, sphere_id)
VALUES ($1, $2)
`

type InsertProjectSphereParams struct {
	ProjectID pgtype.UUID
	SphereID  pgtype.UUID
}

func (q *Queries) InsertProjectSphere(ctx context.Context, arg InsertProjectSphereParams) error {
	_, err := q.db.Exec(ctx, insertProjectSphere, arg.ProjectID, arg.SphereID)
	return err
}

const listProjectsBySphere = `-- name: ListProjectsBySphere :many
SELECT p.id, p.user_id, p.name, p.description, p.status, p.outcome, p.target_value, p.current_value, p.unit, p.target_date, p.created_at, p.updated_at
FROM projects p
JOIN project_spheres ps ON ps.project_id = p.id
WHERE p.user_id = $1 AND ps.sphere_id = $2 AND p.status = 'active'
ORDER BY p.created_at ASC
`

type ListProjectsBySphereParams struct {
	UserID   pgtype.UUID
	SphereID pgtype.UUID
}

type ListProjectsBySphereRow struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Name         string
	Description  pgtype.Text
	Status       string
	Outcome      pgtype.Text
	TargetValue  pgtype.Numeric
	CurrentValue pgtype.Numeric
	Unit         pgtype.Text
	TargetDate   pgtype.Date
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) ListProjectsBySphere(ctx context.Context, arg ListProjectsBySphereParams) ([]ListProjectsBySphereRow, error) {
	rows, err := q.db.Query(ctx, listProjectsBySphere, arg.UserID, arg.SphereID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsBySphereRow{}
	for rows.Next() {
		var i ListProjectsBySphereRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.Outcome,
			&i.TargetValue,
			&i.CurrentValue,
			&i.Unit,
			&i.TargetDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSphereIDsByProject = `-- name: ListSphereIDsByProject :many
SELECT sphere_id FROM project_spheres WHERE project_id = $1
`

func (q *Queries) ListSphereIDsByProject(ctx context.Context, projectID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listSphereIDsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var sphere_id pgtype.UUID
		if err := rows.Scan(&sphere_id); err != nil {
			return nil, err
		}
		items = append(items, sphere_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
