// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findProjectByName = `-- name: FindProjectByName :one
SELECT id, user_id, name, description, status, outcome, target_value, current_value, unit, target_date, created_at, updated_at
FROM projects
WHERE user_id = $1 AND lower(name) = lower($2) AND status = 'active'
`

type FindProjectByNameParams struct {
	UserID pgtype.UUID
	Lower  string
}

type FindProjectByNameRow struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Name         string
	Description  pgtype.Text
	Status       string
	Outcome      pgtype.Text
	TargetValue  pgtype.Numeric
	CurrentValue pgtype.Numeric
	Unit         pgtype.Text
	TargetDate   pgtype.Date
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) FindProjectByName(ctx context.Context, arg FindProjectByNameParams) (FindProjectByNameRow, error) {
	row := q.db.QueryRow(ctx, findProjectByName, arg.UserID, arg.Lower)
	var i FindProjectByNameRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Outcome,
		&i.TargetValue,
		&i.CurrentValue,
		&i.Unit,
		&i.TargetDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, user_id, name, description, status, outcome, target_value, current_value, unit, target_date, created_at, updated_at
FROM projects
WHERE id = $1 AND user_id = $2
`

type GetProjectByIDParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetProjectByIDRow struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Name         string
	Description  pgtype.Text
	Status       string
	Outcome      pgtype.Text
	TargetValue  pgtype.Numeric
	CurrentValue pgtype.Numeric
	Unit         pgtype.Text
	TargetDate   pgtype.Date
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (GetProjectByIDRow, error) {
	row := q.db.QueryRow(ctx, getProjectByID, arg.ID, arg.UserID)
	var i GetProjectByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Outcome,
		&i.TargetValue,
		&i.CurrentValue,
		&i.Unit,
		&i.TargetDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProject = `-- name: InsertProject :exec
INSERT INTO projects (id, user_id, name, description, status, outcome, target_value, current_value, unit, target_date, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertProjectParams struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Name         string
	Description  pgtype.Text
	Status       string
	Outcome      pgtype.Text
	TargetValue  pgtype.Numeric
	CurrentValue pgtype.Numeric
	Unit         pgtype.Text
	TargetDate   pgtype.Date
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) error {
	_, err := q.db.Exec(ctx, insertProject,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Outcome,
		arg.TargetValue,
		arg.CurrentValue,
		arg.Unit,
		arg.TargetDate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listActiveProjects = `-- name: ListActiveProjects :many
SELECT id, user_id, name, description, status, outcome, target_value, current_value, unit, target_date, created_at, updated_at
FROM projects
WHERE user_id = $1 AND status = 'active'
ORDER BY created_at ASC
`

type ListActiveProjectsRow struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Name         string
	Description  pgtype.Text
	Status       string
	Outcome      pgtype.Text
	TargetValue  pgtype.Numeric
	CurrentValue pgtype.Numeric
	Unit         pgtype.Text
	TargetDate   pgtype.Date
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) ListActiveProjects(ctx context.Context, userID pgtype.UUID) ([]ListActiveProjectsRow, error) {
	rows, err := q.db.Query(ctx, listActiveProjects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveProjectsRow{}
	for rows.Next() {
		var i ListActiveProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.Outcome,
			&i.TargetValue,
			&i.CurrentValue,
			&i.Unit,
			&i.TargetDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectExists = `-- name: ProjectExists :one
SELECT EXISTS (
    SELECT 1 FROM projects WHERE id = $1 AND user_id = $2 AND status = 'active'
) AS exists
`

type ProjectExistsParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) ProjectExists(ctx context.Context, arg ProjectExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, projectExists, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const projectsExist = `-- name: ProjectsExist :one
SELECT count(*)::int = $1::int AS all_exist
FROM projects
WHERE user_id = $2
  AND status = 'active'
  AND id = ANY($3::uuid[])
`

type ProjectsExistParams struct {
	Expected   int32
	UserID     pgtype.UUID
	ProjectIds []pgtype.UUID
}

func (q *Queries) ProjectsExist(ctx context.Context, arg ProjectsExistParams) (bool, error) {
	row := q.db.QueryRow(ctx, projectsExist, arg.Expected, arg.UserID, arg.ProjectIds)
	var all_exist bool
	err := row.Scan(&all_exist)
	return all_exist, err
}

const updateProjectStatus = `-- name: UpdateProjectStatus :exec
UPDATE projects
SET status = $3, updated_at = now()
WHERE id = $1 AND user_id = $2
`

type UpdateProjectStatusParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
	Status string
}

func (q *Queries) UpdateProjectStatus(ctx context.Context, arg UpdateProjectStatusParams) error {
	_, err := q.db.Exec(ctx, updateProjectStatus, arg.ID, arg.UserID, arg.Status)
	return err
}
