// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review_stats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCompletedTasksBetween = `-- name: CountCompletedTasksBetween :one
SELECT COUNT(*)::bigint AS total
FROM tasks
WHERE user_id = $1
  AND status = 'done'
  AND completed_at >= $2
  AND completed_at < $3
  AND deleted_at IS NULL
`

type CountCompletedTasksBetweenParams struct {
	UserID        pgtype.UUID
	CompletedAt   pgtype.Timestamptz
	CompletedAt_2 pgtype.Timestamptz
}

func (q *Queries) CountCompletedTasksBetween(ctx context.Context, arg CountCompletedTasksBetweenParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCompletedTasksBetween, arg.UserID, arg.CompletedAt, arg.CompletedAt_2)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countHabitCompletionsBetween = `-- name: CountHabitCompletionsBetween :one
SELECT COUNT(*)::bigint AS total
FROM habit_logs hl
JOIN habits h ON h.id = hl.habit_id
WHERE h.user_id = $1
  AND hl.completed = true
  AND hl.log_date >= $2
  AND hl.log_date < $3
`

type CountHabitCompletionsBetweenParams struct {
	UserID    pgtype.UUID
	LogDate   pgtype.Date
	LogDate_2 pgtype.Date
}

func (q *Queries) CountHabitCompletionsBetween(ctx context.Context, arg CountHabitCompletionsBetweenParams) (int64, error) {
	row := q.db.QueryRow(ctx, countHabitCompletionsBetween, arg.UserID, arg.LogDate, arg.LogDate_2)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countOpenTasks = `-- name: CountOpenTasks :one
SELECT COUNT(*)::bigint AS total
FROM tasks
WHERE user_id = $1
  AND status IN ('todo', 'in_progress')
  AND deleted_at IS NULL
`

func (q *Queries) CountOpenTasks(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenTasks, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}
