// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduled_jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelPendingReminder = `-- name: CancelPendingReminder :one
UPDATE scheduled_jobs
SET status = 'cancelled', updated_at = now()
WHERE id = $1 AND user_id = $2 AND job_type = 'reminder' AND status = 'pending'
RETURNING id, user_id, job_type, payload, run_at, status, channel, created_at
`

type CancelPendingReminderParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type CancelPendingReminderRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	JobType   string
	Payload   []byte
	RunAt     pgtype.Timestamptz
	Status    string
	Channel   string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CancelPendingReminder(ctx context.Context, arg CancelPendingReminderParams) (CancelPendingReminderRow, error) {
	row := q.db.QueryRow(ctx, cancelPendingReminder, arg.ID, arg.UserID)
	var i CancelPendingReminderRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobType,
		&i.Payload,
		&i.RunAt,
		&i.Status,
		&i.Channel,
		&i.CreatedAt,
	)
	return i, err
}

const claimDueJobs = `-- name: ClaimDueJobs :many
WITH picked AS (
    SELECT sj.id
    FROM scheduled_jobs sj
    WHERE sj.status = 'pending' AND sj.run_at <= $1
    ORDER BY sj.run_at
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
UPDATE scheduled_jobs AS j
SET status = 'processing', updated_at = now()
FROM picked
WHERE j.id = picked.id
RETURNING j.id, j.user_id, j.job_type, j.payload, j.run_at, j.status, j.channel
`

type ClaimDueJobsParams struct {
	RunAt pgtype.Timestamptz
	Limit int32
}

type ClaimDueJobsRow struct {
	ID      pgtype.UUID
	UserID  pgtype.UUID
	JobType string
	Payload []byte
	RunAt   pgtype.Timestamptz
	Status  string
	Channel string
}

func (q *Queries) ClaimDueJobs(ctx context.Context, arg ClaimDueJobsParams) ([]ClaimDueJobsRow, error) {
	rows, err := q.db.Query(ctx, claimDueJobs, arg.RunAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimDueJobsRow{}
	for rows.Next() {
		var i ClaimDueJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.JobType,
			&i.Payload,
			&i.RunAt,
			&i.Status,
			&i.Channel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasPendingJob = `-- name: HasPendingJob :one
SELECT EXISTS (
    SELECT 1 FROM scheduled_jobs
    WHERE user_id = $1 AND job_type = $2 AND status = 'pending'
) AS exists
`

type HasPendingJobParams struct {
	UserID  pgtype.UUID
	JobType string
}

func (q *Queries) HasPendingJob(ctx context.Context, arg HasPendingJobParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPendingJob, arg.UserID, arg.JobType)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertScheduledJob = `-- name: InsertScheduledJob :one
INSERT INTO scheduled_jobs (id, user_id, job_type, payload, run_at, channel)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertScheduledJobParams struct {
	ID      pgtype.UUID
	UserID  pgtype.UUID
	JobType string
	Payload []byte
	RunAt   pgtype.Timestamptz
	Channel string
}

func (q *Queries) InsertScheduledJob(ctx context.Context, arg InsertScheduledJobParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertScheduledJob,
		arg.ID,
		arg.UserID,
		arg.JobType,
		arg.Payload,
		arg.RunAt,
		arg.Channel,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listPendingRemindersByUser = `-- name: ListPendingRemindersByUser :many
SELECT id, user_id, job_type, payload, run_at, status, channel, created_at
FROM scheduled_jobs
WHERE user_id = $1 AND job_type = 'reminder' AND status = 'pending'
ORDER BY run_at ASC
`

type ListPendingRemindersByUserRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	JobType   string
	Payload   []byte
	RunAt     pgtype.Timestamptz
	Status    string
	Channel   string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListPendingRemindersByUser(ctx context.Context, userID pgtype.UUID) ([]ListPendingRemindersByUserRow, error) {
	rows, err := q.db.Query(ctx, listPendingRemindersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingRemindersByUserRow{}
	for rows.Next() {
		var i ListPendingRemindersByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.JobType,
			&i.Payload,
			&i.RunAt,
			&i.Status,
			&i.Channel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobDone = `-- name: MarkJobDone :exec
UPDATE scheduled_jobs
SET status = 'done', updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkJobDone(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markJobDone, id)
	return err
}

const markJobPending = `-- name: MarkJobPending :exec
UPDATE scheduled_jobs
SET status = 'pending', updated_at = now(), retry_count = retry_count + 1
WHERE id = $1
`

func (q *Queries) MarkJobPending(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markJobPending, id)
	return err
}

const rescheduleJob = `-- name: RescheduleJob :exec
UPDATE scheduled_jobs
SET run_at = $2, status = 'pending', updated_at = now()
WHERE id = $1
`

type RescheduleJobParams struct {
	ID    pgtype.UUID
	RunAt pgtype.Timestamptz
}

func (q *Queries) RescheduleJob(ctx context.Context, arg RescheduleJobParams) error {
	_, err := q.db.Exec(ctx, rescheduleJob, arg.ID, arg.RunAt)
	return err
}

const reschedulePendingJobsByType = `-- name: ReschedulePendingJobsByType :exec
UPDATE scheduled_jobs
SET run_at = $3, status = 'pending', updated_at = now()
WHERE user_id = $1 AND job_type = $2 AND status = 'pending'
`

type ReschedulePendingJobsByTypeParams struct {
	UserID  pgtype.UUID
	JobType string
	RunAt   pgtype.Timestamptz
}

func (q *Queries) ReschedulePendingJobsByType(ctx context.Context, arg ReschedulePendingJobsByTypeParams) error {
	_, err := q.db.Exec(ctx, reschedulePendingJobsByType, arg.UserID, arg.JobType, arg.RunAt)
	return err
}
