// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserSettingsByUserID = `-- name: GetUserSettingsByUserID :one
SELECT user_id, morning_review_at, evening_review_at, weekly_review_at, monthly_review_at,
       quiet_hours_start, quiet_hours_end, language, updated_at
FROM user_settings
WHERE user_id = $1
`

type GetUserSettingsByUserIDRow struct {
	UserID          pgtype.UUID
	MorningReviewAt pgtype.Time
	EveningReviewAt pgtype.Time
	WeeklyReviewAt  pgtype.Time
	MonthlyReviewAt pgtype.Time
	QuietHoursStart pgtype.Time
	QuietHoursEnd   pgtype.Time
	Language        string
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetUserSettingsByUserID(ctx context.Context, userID pgtype.UUID) (GetUserSettingsByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getUserSettingsByUserID, userID)
	var i GetUserSettingsByUserIDRow
	err := row.Scan(
		&i.UserID,
		&i.MorningReviewAt,
		&i.EveningReviewAt,
		&i.WeeklyReviewAt,
		&i.MonthlyReviewAt,
		&i.QuietHoursStart,
		&i.QuietHoursEnd,
		&i.Language,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEveningReviewAt = `-- name: UpdateEveningReviewAt :exec
UPDATE user_settings
SET evening_review_at = $2, updated_at = now()
WHERE user_id = $1
`

type UpdateEveningReviewAtParams struct {
	UserID          pgtype.UUID
	EveningReviewAt pgtype.Time
}

func (q *Queries) UpdateEveningReviewAt(ctx context.Context, arg UpdateEveningReviewAtParams) error {
	_, err := q.db.Exec(ctx, updateEveningReviewAt, arg.UserID, arg.EveningReviewAt)
	return err
}

const updateMorningReviewAt = `-- name: UpdateMorningReviewAt :exec
UPDATE user_settings
SET morning_review_at = $2, updated_at = now()
WHERE user_id = $1
`

type UpdateMorningReviewAtParams struct {
	UserID          pgtype.UUID
	MorningReviewAt pgtype.Time
}

func (q *Queries) UpdateMorningReviewAt(ctx context.Context, arg UpdateMorningReviewAtParams) error {
	_, err := q.db.Exec(ctx, updateMorningReviewAt, arg.UserID, arg.MorningReviewAt)
	return err
}

const updateQuietHours = `-- name: UpdateQuietHours :exec
UPDATE user_settings
SET quiet_hours_start = $2, quiet_hours_end = $3, updated_at = now()
WHERE user_id = $1
`

type UpdateQuietHoursParams struct {
	UserID          pgtype.UUID
	QuietHoursStart pgtype.Time
	QuietHoursEnd   pgtype.Time
}

func (q *Queries) UpdateQuietHours(ctx context.Context, arg UpdateQuietHoursParams) error {
	_, err := q.db.Exec(ctx, updateQuietHours, arg.UserID, arg.QuietHoursStart, arg.QuietHoursEnd)
	return err
}
