// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spheres.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSpheresByUser = `-- name: CountSpheresByUser :one
SELECT count(*)::int FROM life_spheres WHERE user_id = $1
`

func (q *Queries) CountSpheresByUser(ctx context.Context, userID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countSpheresByUser, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteSphereByUser = `-- name: DeleteSphereByUser :one
DELETE FROM life_spheres
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, sort_order, created_at, updated_at
`

type DeleteSphereByUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteSphereByUser(ctx context.Context, arg DeleteSphereByUserParams) (LifeSphere, error) {
	row := q.db.QueryRow(ctx, deleteSphereByUser, arg.ID, arg.UserID)
	var i LifeSphere
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findSphereByName = `-- name: FindSphereByName :one
SELECT id, user_id, name, sort_order, created_at, updated_at
FROM life_spheres
WHERE user_id = $1 AND lower(name) = lower($2)
`

type FindSphereByNameParams struct {
	UserID pgtype.UUID
	Name   string
}

func (q *Queries) FindSphereByName(ctx context.Context, arg FindSphereByNameParams) (LifeSphere, error) {
	row := q.db.QueryRow(ctx, findSphereByName, arg.UserID, arg.Name)
	var i LifeSphere
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSphereByUser = `-- name: GetSphereByUser :one
SELECT id, user_id, name, sort_order, created_at, updated_at
FROM life_spheres
WHERE id = $1 AND user_id = $2
`

type GetSphereByUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetSphereByUser(ctx context.Context, arg GetSphereByUserParams) (LifeSphere, error) {
	row := q.db.QueryRow(ctx, getSphereByUser, arg.ID, arg.UserID)
	var i LifeSphere
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSphere = `-- name: InsertSphere :exec
INSERT INTO life_spheres (id, user_id, name, sort_order, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertSphereParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	SortOrder int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) InsertSphere(ctx context.Context, arg InsertSphereParams) error {
	_, err := q.db.Exec(ctx, insertSphere,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listSpheresByUser = `-- name: ListSpheresByUser :many
SELECT id, user_id, name, sort_order, created_at, updated_at
FROM life_spheres
WHERE user_id = $1
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListSpheresByUser(ctx context.Context, userID pgtype.UUID) ([]LifeSphere, error) {
	rows, err := q.db.Query(ctx, listSpheresByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LifeSphere{}
	for rows.Next() {
		var i LifeSphere
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSphere = `-- name: UpdateSphere :exec
UPDATE life_spheres
SET name = $3, sort_order = $4, updated_at = $5
WHERE id = $1 AND user_id = $2
`

type UpdateSphereParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	SortOrder int32
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateSphere(ctx context.Context, arg UpdateSphereParams) error {
	_, err := q.db.Exec(ctx, updateSphere,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.SortOrder,
		arg.UpdatedAt,
	)
	return err
}
