// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_spheres.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTaskSpheres = `-- name: DeleteTaskSpheres :exec
DELETE FROM task_spheres WHERE task_id = $1
`

func (q *Queries) DeleteTaskSpheres(ctx context.Context, taskID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTaskSpheres, taskID)
	return err
}

const insertTaskSphere = `-- name: InsertTaskSphere :exec
INSERT INTO task_spheres (task_id, sphere_id)
VALUES ($1, $2)
`

type InsertTaskSphereParams struct {
	TaskID   pgtype.UUID
	SphereID pgtype.UUID
}

func (q *Queries) InsertTaskSphere(ctx context.Context, arg InsertTaskSphereParams) error {
	_, err := q.db.Exec(ctx, insertTaskSphere, arg.TaskID, arg.SphereID)
	return err
}

const listSphereIDsByTask = `-- name: ListSphereIDsByTask :many
SELECT sphere_id FROM task_spheres WHERE task_id = $1
`

func (q *Queries) ListSphereIDsByTask(ctx context.Context, taskID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listSphereIDsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var sphere_id pgtype.UUID
		if err := rows.Scan(&sphere_id); err != nil {
			return nil, err
		}
		items = append(items, sphere_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
