// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTaskProjects = `-- name: DeleteTaskProjects :exec
DELETE FROM task_projects WHERE task_id = $1
`

func (q *Queries) DeleteTaskProjects(ctx context.Context, taskID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTaskProjects, taskID)
	return err
}

const insertTaskProject = `-- name: InsertTaskProject :exec
INSERT INTO task_projects (task_id, project_id)
VALUES ($1, $2)
`

type InsertTaskProjectParams struct {
	TaskID    pgtype.UUID
	ProjectID pgtype.UUID
}

func (q *Queries) InsertTaskProject(ctx context.Context, arg InsertTaskProjectParams) error {
	_, err := q.db.Exec(ctx, insertTaskProject, arg.TaskID, arg.ProjectID)
	return err
}

const listProjectIDsByTask = `-- name: ListProjectIDsByTask :many
SELECT project_id FROM task_projects WHERE task_id = $1
`

func (q *Queries) ListProjectIDsByTask(ctx context.Context, taskID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listProjectIDsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var project_id pgtype.UUID
		if err := rows.Scan(&project_id); err != nil {
			return nil, err
		}
		items = append(items, project_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByProjectJoin = `-- name: ListTasksByProjectJoin :many
SELECT t.id, t.user_id, t.title, t.description, t.status, t.priority, t.due_date, t.completed_at, t.deleted_at, t.created_at, t.updated_at, t.duration_minutes, t.tags, t.kind, t.address, t.note_id
FROM tasks t
JOIN task_projects tp ON tp.task_id = t.id
WHERE t.user_id = $1
  AND tp.project_id = $2
  AND t.deleted_at IS NULL
  AND t.status IN ('todo', 'in_progress', 'done')
ORDER BY
    CASE t.status WHEN 'done' THEN 1 ELSE 0 END,
    t.due_date ASC NULLS LAST,
    t.created_at ASC
`

type ListTasksByProjectJoinParams struct {
	UserID    pgtype.UUID
	ProjectID pgtype.UUID
}

func (q *Queries) ListTasksByProjectJoin(ctx context.Context, arg ListTasksByProjectJoinParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByProjectJoin, arg.UserID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.CompletedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DurationMinutes,
			&i.Tags,
			&i.Kind,
			&i.Address,
			&i.NoteID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
