// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findOpenTaskByTitle = `-- name: FindOpenTaskByTitle :one
SELECT id, user_id, title, description, status, priority, due_date, completed_at, deleted_at, created_at, updated_at
FROM tasks
WHERE user_id = $1
  AND deleted_at IS NULL
  AND status IN ('todo', 'in_progress')
  AND title ILIKE '%' || $2 || '%'
ORDER BY
    CASE WHEN lower(title) = lower($2) THEN 0 ELSE 1 END,
    due_date ASC NULLS LAST,
    created_at ASC
LIMIT 1
`

type FindOpenTaskByTitleParams struct {
	UserID  pgtype.UUID
	Column2 pgtype.Text
}

func (q *Queries) FindOpenTaskByTitle(ctx context.Context, arg FindOpenTaskByTitleParams) (Task, error) {
	row := q.db.QueryRow(ctx, findOpenTaskByTitle, arg.UserID, arg.Column2)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, user_id, title, description, status, priority, due_date, completed_at, deleted_at, created_at, updated_at
FROM tasks
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetTaskByIDParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTask = `-- name: InsertTask :one
INSERT INTO tasks (
    id, user_id, title, description, status, priority, due_date, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $8
)
RETURNING id, user_id, title, description, status, priority, due_date, completed_at, deleted_at, created_at, updated_at
`

type InsertTaskParams struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Title       string
	Description pgtype.Text
	Status      string
	Priority    string
	DueDate     pgtype.Date
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, insertTask,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueDate,
		arg.CreatedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasksByDueDate = `-- name: ListTasksByDueDate :many
SELECT id, user_id, title, description, status, priority, due_date, completed_at, deleted_at, created_at, updated_at
FROM tasks
WHERE user_id = $1
  AND due_date = $2
  AND deleted_at IS NULL
ORDER BY
    CASE priority
        WHEN 'urgent' THEN 4
        WHEN 'high' THEN 3
        WHEN 'medium' THEN 2
        WHEN 'low' THEN 1
    END DESC,
    created_at ASC
`

type ListTasksByDueDateParams struct {
	UserID  pgtype.UUID
	DueDate pgtype.Date
}

func (q *Queries) ListTasksByDueDate(ctx context.Context, arg ListTasksByDueDateParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByDueDate, arg.UserID, arg.DueDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.CompletedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET status = $3,
    completed_at = $4,
    updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, title, description, status, priority, due_date, completed_at, deleted_at, created_at, updated_at
`

type UpdateTaskParams struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Status      string
	CompletedAt pgtype.Timestamptz
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.UserID,
		arg.Status,
		arg.CompletedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
