// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telegram_sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTelegramSession = `-- name: GetTelegramSession :one
SELECT user_id, chat_id, dashboard_message_id, state, state_payload, updated_at
FROM telegram_sessions
WHERE user_id = $1
`

func (q *Queries) GetTelegramSession(ctx context.Context, userID pgtype.UUID) (TelegramSession, error) {
	row := q.db.QueryRow(ctx, getTelegramSession, userID)
	var i TelegramSession
	err := row.Scan(
		&i.UserID,
		&i.ChatID,
		&i.DashboardMessageID,
		&i.State,
		&i.StatePayload,
		&i.UpdatedAt,
	)
	return i, err
}

const setTelegramDashboard = `-- name: SetTelegramDashboard :exec
UPDATE telegram_sessions
SET chat_id = $2,
    dashboard_message_id = $3,
    updated_at = now()
WHERE user_id = $1
`

type SetTelegramDashboardParams struct {
	UserID             pgtype.UUID
	ChatID             int64
	DashboardMessageID pgtype.Int8
}

func (q *Queries) SetTelegramDashboard(ctx context.Context, arg SetTelegramDashboardParams) error {
	_, err := q.db.Exec(ctx, setTelegramDashboard, arg.UserID, arg.ChatID, arg.DashboardMessageID)
	return err
}

const setTelegramState = `-- name: SetTelegramState :exec
UPDATE telegram_sessions
SET state = $2,
    state_payload = $3,
    updated_at = now()
WHERE user_id = $1
`

type SetTelegramStateParams struct {
	UserID       pgtype.UUID
	State        string
	StatePayload []byte
}

func (q *Queries) SetTelegramState(ctx context.Context, arg SetTelegramStateParams) error {
	_, err := q.db.Exec(ctx, setTelegramState, arg.UserID, arg.State, arg.StatePayload)
	return err
}

const upsertTelegramSession = `-- name: UpsertTelegramSession :exec
INSERT INTO telegram_sessions (user_id, chat_id, dashboard_message_id, state, state_payload, updated_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (user_id) DO UPDATE
SET chat_id = EXCLUDED.chat_id,
    dashboard_message_id = COALESCE(EXCLUDED.dashboard_message_id, telegram_sessions.dashboard_message_id),
    state = EXCLUDED.state,
    state_payload = EXCLUDED.state_payload,
    updated_at = now()
`

type UpsertTelegramSessionParams struct {
	UserID             pgtype.UUID
	ChatID             int64
	DashboardMessageID pgtype.Int8
	State              string
	StatePayload       []byte
}

func (q *Queries) UpsertTelegramSession(ctx context.Context, arg UpsertTelegramSessionParams) error {
	_, err := q.db.Exec(ctx, upsertTelegramSession,
		arg.UserID,
		arg.ChatID,
		arg.DashboardMessageID,
		arg.State,
		arg.StatePayload,
	)
	return err
}
